# Generated by Django 5.1.3 on 2025-01-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='CafeImage',
        ),
    ]
